config/routes.rb
Rails.application.routes.draw do
  root 'periods#index'

  get 'start_period' => 'periods#start_period'

  get 'end_period' => 'periods#end_period'

  devise_for :users
  resources :periods

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/period.rb
class Period < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :periods


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :set_period, only: [:show, :edit, :update, :destroy]

  # GET /periods
  # GET /periods.json
  def index
    @current_period = Period.where(user_id: current_user.id).last
    @periods = Period.all
  end

  def start_period
    Period.create(user_id: current_user.id, start_date: Time.now)
    redirect_to root_path
  end

  def end_period
    Period.where(user_id: current_user.id).last.update(end_date: Time.now)
    redirect_to root_path
  end

  # GET /periods/1
  # GET /periods/1.json
  def show
  end

  # GET /periods/new
  def new
    @period = Period.new
  end

  # GET /periods/1/edit
  def edit
  end

  # POST /periods
  # POST /periods.json
  def create
    @period = Period.new(period_params)

    respond_to do |format|
      if @period.save
        format.html { redirect_to @period, notice: 'Period was successfully created.' }
        format.json { render :show, status: :created, location: @period }
      else
        format.html { render :new }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periods/1
  # PATCH/PUT /periods/1.json
  def update
    respond_to do |format|
      if @period.update(period_params)
        format.html { redirect_to @period, notice: 'Period was successfully updated.' }
        format.json { render :show, status: :ok, location: @period }
      else
        format.html { render :edit }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
  def destroy
    @period.destroy
    respond_to do |format|
      format.html { redirect_to periods_url, notice: 'Period was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_period
      @period = Period.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def period_params
      params.require(:period).permit(:start_date, :end_date, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
	def on_my_period?(period)
		if period != nil && period.end_date == nil
			return true
		else
			return false
		end
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Galendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">GALENDAR </a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Periods</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <div class="jumbotron">
        <h1>Welcome to Galendar</h1> 
        <p>Keep track of your period.</p> 
      </div>
    </div>


    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/periods/_form.html.erb
<%= form_with(model: period, local: true) do |form| %>
  <% if period.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(period.errors.count, "error") %> prohibited this period from being saved:</h2>

      <ul>
      <% period.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.number_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.number_field :end_date %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/periods/edit.html.erb
<h1>Editing Period</h1>

<%= render 'form', period: @period %>

<%= link_to 'Show', @period %> |
<%= link_to 'Back', periods_path %>

app/views/periods/index.html.erb
<p id="notice"><%= notice %></p>

<% if on_my_period?(@current_period)%>
  <%= link_to end_period_path do %>
    End Period
  <% end %>

<% else %>
  <%= link_to start_period_path do %>
    Start Period
  <% end %> 
<% end %>

<h1>Periods</h1>

<table <id id="period"></id>>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @periods.each do |period| %>
      <tr>
        <td><%= period.start_date.strftime("%m/%d/%y") %></td>
        <td><%= period.end_date.strftime("%m/%d/%y") %></td>
        <td><%= period.user_id %></td>
        <td><%= link_to 'Show', period %></td>
        <td><%= link_to 'Edit', edit_period_path(period) %></td>
        <td><%= link_to 'Destroy', period, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/periods/new.html.erb
<h1>New Period</h1>

<%= render 'form', period: @period %>

<%= link_to 'Back', periods_path %>

app/views/periods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @period.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @period.end_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @period.user_id %>
</p>

<%= link_to 'Edit', edit_period_path(@period) %> |
<%= link_to 'Back', periods_path %>